export const LANG_RU_NAME = 'ru';
export const LANG_RU_TRANS = {
    'Product Management System': 'Система менеджмента продуктов',
    'You logged as': 'Добро пожаловать,',
    'Login': 'Войти',
    'Welcome to product management system': 'Добро пожаловать в систему менеджмента продуктов',
    'Logout': 'Выйти',
    'Close': 'Закрыть',
    'User': 'Пользователи',
    'Product': 'Продукты',
    'Stock': 'Склады',
    'Store': 'Магазины',
    'Users administration': 'Администрирование пользователей',
    'Users in system': 'Пользователи в системе',
    'Create user': 'Создать пользователя',
    'Create User Form': 'Форма создания пользователя',
    'Username': 'Имя пользователя',
    'Username is required': 'Имя пользователя обязательно!',
    'Password': 'Пароль',
    'Password is required': 'Пароль обязателен!',
    'Available authorities(click to add)': 'Доступные роли(ЛКМ - добавить)',
    'Selected authorities(click to remove)': 'Выбранные роли(ЛКМ - удалить)',
    'Submit': 'Добавить',
    'Edit': 'Редактировать',
    'Remove': 'Удалить',
    'Edit User Form': 'Форма редактирования пользователя',
    'Products management': 'Медеджмент продуктов',
    'Navigation' : 'Навигация',
    'All products': 'Все продукты',
    'Add product': 'Добавить продукт',
    'Search': 'Поиск',
    'Total:': 'Всего:',
    'Found products': 'Найденные продукты',
    'items in page': 'единиц на странице',
    'Name': 'Название',
    'Cost': 'Стоимость',
    'Type': 'Тип',
    'Details': 'Описание',
    'Operations': 'Действия',
    'Page': 'Страница',
    'Prev': 'Пред',
    'Next': 'След',
    'Create Product Form': 'Форма добавления продукта',
    'Must be 0-500 characters long': 'Длина должна быть 0-500 символов',
    'Edit Product Form': 'Форма редактирования продукта',
    'Search page': 'Страница поиска',
    'Search in catalog': 'Поиск в каталоге',
    'Stock management': 'Менеджмент складов',
    'Stock list': 'Список складов',
    'Create stock': 'Добавить склад',
    'Found stock list': 'Найденные склады',
    'Specialize': 'Специализация',
    'Products': 'Продукты',
    'Address': 'Адрес',
    'Phone': 'Телефон',
    'Square': 'Площадь',
    'Create Stock Form': 'Форма добавления продукта',
    'Update Stock Form': 'Форма редактирования продукта',
    'Phone number must contain only digits and length must be 5-20 symbols!': 'Номер телефона может содержать только цифры и быть длиной 5-20 символов!',
    'Available products(click to add)': 'Доступные продукты(ЛКМ - добавить)',
    'Selected products(click to remove)': 'Выбранные продукты(ЛКМ - удалить)',
    'Store management': 'Менеджмент магазинов',
    'Store list': 'Список магазинов',
    'Create store': 'Добавить магазин',
    'All stores in system': 'Все магазины в системе',
    'More': 'Подробнее',
    'Create store form': 'Форма добавления магазина',
    'Mail': 'Почта',
    'Discounts': 'Система скидок',
    'Available stocks(click to add)': 'Доступные склады',
    'Selected stocks(click to remove)': 'Сотрудничающие склады',
    'Edit store form': 'Форма редактирования магазина',
    'Welcome to': 'Добро пожаловать в',
    'Contact with us': 'Связь с магазином',
    'Available products in store': 'Продукты, доступные в магазине',
    'Parameter': 'Параметры поиска',
    'Choose search parameters': 'Выберите параметры поиска',
    'true': 'Присутствует',
    'false': 'Отсутствует',
    'Width(sm)': 'Ширина(см)',
    'Height(sm)': 'Высота(см)',
    'Weight(kg)': 'Вес(кг)',
    'Logo': 'Логотип'
};