export const LANG_RU_NAME = 'ru';
export const LANG_RU_TRANS = {
    'Product Management System': 'Система менеджмента продуктов',
    'You logged as': 'Добро пожаловать,',
    'Login': 'Войти',
    'Welcome to product management system': 'Добро пожаловать в систему менеджмента продуктов',
    'Logout': 'Выйти',
    'Close': 'Закрыть',
    'User': 'Пользователи',
    'Product': 'Продукты',
    'Stock': 'Склады',
    'Store': 'Магазины',
    'Users administration': 'Администрирование пользователей',
    'Users in system': 'Пользователи в системе',
    'Create user': 'Создать пользователя',
    'Create User Form': 'Форма создания пользователя',
    'Username': 'Имя пользователя',
    'Username is required': 'Имя пользователя обязательно!',
    'Password': 'Пароль',
    'Password is required': 'Пароль обязателен!',
    'Available authorities(click to add)': 'Доступные роли(ЛКМ - добавить)',
    'Selected authorities(click to remove)': 'Выбранные роли(ЛКМ - удалить)',
    'Submit': 'Добавить',
    'Edit': 'Редактировать',
    'Remove': 'Удалить',
    'Edit User Form': 'Форма редактирования пользователя',
    'Products management': 'Медеджмент продуктов',
    'Navigation' : 'Навигация',
    'All products': 'Все продукты',
    'Add product': 'Добавить продукт',
    'Search': 'Поиск',
    'Total:': 'Всего:',
    'Found products': 'Найденные продукты',
    'items in page': 'вещей на странице',
    'Name': 'Название',
    'Cost': 'Стоимость',
    'Type': 'Тип',
    'Details': 'Описание',
    'Operations': 'Действия',
    'Page': 'Страница',
    'Prev': 'Пред',
    'Next': 'След'
};